### PR TITLE
fix(html): add destroy

### LINKED ISSUE #689: Bug: StoreError: DESTROYED when using VideoProvider with React StrictMode
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which package(s) or projects are affected?

React (@videojs/react), Core (@videojs/core)

### Browser/OS/Node environment

  - @videojs/react: 10.0.0-alpha.4
  - @videojs/core: 10.0.0-alpha.4
  - @videojs/store: 10.0.0-alpha.4
  - React: 19.0.0
  - Vite: 6.2.1
  - Node: 22.x
  - OS: macOS

### Description

Using any `@videojs/react` Provider component (e.g., `VideoProvider` from the video preset or a custom `createPlayer` Provider) inside React's `<StrictMode>` throws `StoreError: DESTROYED` on mount.

### Reduced test case

_No response_

### Steps to reproduce

1. Create a Vite + React project:
```
  npm create vite@latest vjs-repro -- --template react-ts
  cd vjs-repro
  npm install
  npm install @videojs/react@next
```

  2. Replace src/App.tsx with:
 
```
  import { VideoProvider, Video } from '@videojs/react/video';
  import { Container } from '@videojs/react';

  function App() {
    return (
      <VideoProvider>
        <Container>
          <Video src="https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_1MB.mp4" />
        </Container>
      </VideoProvider>
    );
  }

  export default App;
```

  3. Confirm src/main.tsx uses <StrictMode> (the Vite default):
```
  import { StrictMode } from 'react'
  import { createRoot } from 'react-dom/client'
  import App from './App.tsx'

  createRoot(document.getElementById('root')!).render(
    <StrictMode>
      <App />
    </StrictMode>,
  )
```
  4. Run the dev server: `npm run dev`
  5. Open the browser console.

### Current Behavior

The app crashes with an error boundary or blank screen.

### Root Cause

In packages/react/src/player/create-player.tsx, the Provider creates the store via useState and destroys it in a useEffect cleanup:

```
  function Provider({ children }) {
    const [store] = useState(() => createStore()(combine(...config.features)));
    const [media, setMedia] = useState(null);
    useEffect(() => () => store.destroy(), [store]);  // ← problem here
    // ...
  }
```

React StrictMode simulates an unmount/remount cycle in development:

  1. Mount — useState initializer creates a fresh store
  2. Effect runs — registers cleanup: () => store.destroy()
  3. StrictMode simulated unmount — cleanup runs, store.destroy() is called, setting destroyed = true
  4. StrictMode simulated remount — effects re-run, but useState returns the same (now destroyed) store instance
  5. Container effect — calls store.attach(...), which checks if (destroyed) throwDestroyedError() → crash

### Suggested Fix (Claude):

Replace the useState + useEffect pattern with one that can recover from StrictMode's double-mount. For example, using useRef to detect and recreate a destroyed store:

```
  function Provider({ children }) {
    const storeRef = useRef(null);
    if (!storeRef.current || storeRef.current.destroyed) {
      storeRef.current = createStore()(combine(...config.features));
    }
    const store = storeRef.current;
    const [media, setMedia] = useState(null);
    useEffect(() => () => { store.destroy(); }, [store]);
    // ...
  }
```

This way, when `StrictMode` remounts and the effect re-runs, the render phase detects the destroyed store and creates a fresh one before Container tries to `attach()`.

### Workaround:

Remove <StrictMode> from the app's entry point.

### Expected Behavior

  The player renders without errors.

### Errors

Uncaught StoreError: DESTROYED
      at throwDestroyedError (store.js)
      at Object.attach (store.js)
      at context.js
      ...

### What version of the package are you using?

10.0.0-alpha.4

### PR DESCRIPTION
**Pull request by mihar-22**
Closes #689

## Summary

Prevents `StoreError: DESTROYED` when frameworks (React, Lit, etc.) temporarily disconnect and reconnect custom elements during reconciliation. Elements now defer destruction by 2 rAF ticks after disconnect — if still disconnected, they destroy; if reconnected, the `isConnected` check skips destruction.

## Changes

- `DestroyMixin` in `@videojs/element` — composable mixin on `ReactiveElement` that adds `destroy()`, `destroyCallback()`, `destroyed`, deferred 2-rAF destruction on disconnect, `keep-alive` attribute opt-out, controller tracking with `hostDestroyed()` notification, and `performUpdate` guard
- `MediaElement` simplified to `DestroyMixin(ReactiveElement)` — all destruction logic lives in the mixin
- `HlsVideo` defers `this.destroy()` by 2 rAFs (goes through delegate proxy to HLS engine)
- Store destruction moved from `disconnectedCallback` to `destroyCallback` in `ProviderMixin`
- Imperative API destruction (slider, popover, thumbnail) moved to `destroyCallback`
- `hostDestroyed?()` added to `ReactiveController` interface

<details>
<summary>Implementation details</summary>

**Why not on `ReactiveElement`?** It's used as a structural type constraint by `SkinMixin` and other composites. Adding public members would break Lit compatibility. The destroy lifecycle lives in `DestroyMixin`; `ReactiveElement` gets a minimal `hostDestroyed?()` hook on the controller interface. See `internal/design/reactive-element-lit-compat.md`.

**Why 2 rAF ticks?** A single rAF can fire before the browser has processed the re-insertion. Two ticks ensure the element has had a full frame to reconnect. The callback checks `isConnected` so reconnected elements survive.

**ContainerMixin unchanged** — It already detaches immediately (lightweight) and re-attaches on reconnect. The store survives because the provider's destruction is deferred.

**HlsVideo uses inline rAFs** — `DestroyMixin` is not applied to `HlsCustomMedia` because it would shadow the delegate-proxied `destroy()` (fixed in #751). Instead, `HlsVideo.disconnectedCallback` schedules the 2-rAF check directly.

</details>

## Testing

```bash
pnpm -F @videojs/element test src/tests/destroy-mixin.test.ts
pnpm -F @videojs/html test
```

13 new tests in `destroy-mixin.test.ts` covering: destroy flag, idempotency, destroyCallback, hostDestroyed notification, connectedCallback guard, performUpdate guard, 2-rAF deferred destruction, reconnect survival, keep-alive attribute.

### CODE REVIEW

File: packages/core/src/core/media/delegate.ts [hunk 1]
```diff
@@ -50,6 +51,10 @@ export function MediaDelegateMixin<Base extends Constructor<any>, Delegate exten
       this.#delegate.detach?.();
       super.detach?.();
     }
+
+    destroy(): void {
+      this.#delegate.destroy?.();
+    }
```
Comment (luwes) [inline packages/core/src/core/media/delegate.ts]: This is not the right way. It was a bug...
See PR https://github.com/videojs/v10/pull/751

**Review by luwes — DISMISSED** [review]

File: packages/core/src/core/media/delegate.ts [hunk 2]
```diff
@@ -3,6 +3,7 @@ import type { Constructor } from '@videojs/utils/types';
 export interface MediaDelegate {
   attach?(target: EventTarget): void;
   detach?(): void;
+  destroy?(): void;
```
Comment (luwes) [inline packages/core/src/core/media/delegate.ts]: Not needed with fix below
