### PR TITLE
fix(packages): remove redundant Shift modifier from playback rate hotkeys

### LINKED ISSUE #1288: Bug: Playback Rate Hotkeys Use Redundant Shift Modifier, Breaking European Layouts
## Bug

The media hotkeys for playback rate (`Shift+>` and `Shift+<` for `speedUp` / `speedDown`) include a redundant `Shift` modifier.

On English keyboards, `>` and `<` are the shifted characters of `.` and `,` — you can't produce them without Shift already held. The `Shift+` prefix adds nothing.

On many European keyboard layouts (French AZERTY, German QWERTZ, Italian, etc.), `<` and `>` live on the same physical key as unshifted/shifted variants. Requiring `shiftKey: true` alongside `key: '<'` makes the binding **impossible to trigger** on these layouts since `{key: '<', shiftKey: true}` can never be produced.

## Fix

Two-part fix:

1. **Bindings**: Define the bindings as simply `>` and `<` without the `Shift` modifier in all skins, design docs, and examples.

2. **Matcher**: Update `matchesHotkeyEvent` to handle **implicit Shift** for non-letter character keys. Characters like `>`, `<`, `?`, `!` require Shift on some layouts but not others — Shift was used to *produce* the character, not as a deliberate modifier. The matcher now ignores `shiftKey` for single non-letter character keys while keeping strict matching for letters (a-z) and named keys (ArrowLeft, Tab, etc.).

## Reported By

Ben on Discord

### PR DESCRIPTION
**Pull request by mihar-22**
Closes #1288
Reference #505 

---

> [!NOTE]
> **Medium Risk**
> Changes core hotkey modifier-matching semantics by ignoring `shiftKey` for single-character non-letter keys unless `Shift` is explicitly part of the binding, which could affect existing shortcut behavior across layouts. Risk is mitigated by expanded unit tests and mostly impacts keyboard handling.
> 
> **Overview**
> Updates playback-rate shortcuts to bind `>`/`<` directly (removing the redundant `Shift+` prefix) across the HTML/React default skins and the hotkey design docs.
> 
> Adjusts `matchesHotkeyEvent` to treat Shift as *implicit* for single non-letter character keys (e.g. `>`, `<`, `?`), so bindings like `>` match regardless of whether Shift was required by the user’s keyboard layout, while explicit bindings like `Shift+>` still require Shift; tests and ARIA formatting expectations are updated accordingly.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 1926e27126b11be69c5df507377e4651f88a7525. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: packages/core/src/dom/hotkey/hotkey.ts [hunk 1]
```diff
@@ -70,6 +70,16 @@ export function parseHotkeyPattern(pattern: string): ParsedHotkeyBinding[] {
   return [{ modifiers, key, originalKey: rawKey }];
 }
 
+/**
+ * Single non-letter character — Shift was used to produce the character itself,
+ * not as a deliberate modifier (e.g. Shift+. → ">", Shift+/ → "?").
+ * Letters excluded because Shift changes case intentionally (k vs K).
+ * Named keys excluded because event.key.length > 1 (ArrowLeft, Tab, etc.).
+ */
+function isImplicitShift(key: string): boolean {
```
Comment (cjpillsbury) [inline packages/core/src/dom/hotkey/hotkey.ts:79]: praise: 😎
